fix(user api) fix user update api error
longguikeji/arkid pull request #255
Opened 2021-03-29 10:31 UTC by fanhe-lg

2021-04-01 03:47 UTC, RockLi commented on api/v1/serializers/external_idp.py
> +            external_idp.order_no = validated_data.get("order_no")
这三行应该在if的外面 不应该if体里面

2021-04-01 03:48 UTC, RockLi commented on api/v1/serializers/user.py
> +        field_name="id",
单引号

2021-04-01 03:49 UTC, RockLi commented on api/v1/serializers/external_idp.py
> +            "order_no",
`order_no`的计算不应该丢给前端


接口部分应该至少以下几个：

1. move up
2. move down
3. move to the top
4. move to the bottom
5. batch update

2021-04-01 03:50 UTC, RockLi commented
现在这个PR已经在两个事情了，需要修改对应的PR标题 描述等

2021-04-01 03:50 UTC, RockLi requested changes
no more comments

2021-04-05 12:55 UTC, RockLi commented
@jinji-hanbin please do the code review

2021-04-06 08:17 UTC, fanhe-lg commented
@RockLi 添加了idp api tags方便前端排序，解决了合并冲突https://github.com/longguikeji/arkid/pull/255/commits/bff7a94c6285eb0b0f20c835a2c1a83b37e586a6

2021-04-06 09:13 UTC, RockLi commented
> @RockLi 添加了idp api tags方便前端排序，解决了合并冲突[bff7a94](https://github.com/longguikeji/arkid/commit/bff7a94c6285eb0b0f20c835a2c1a83b37e586a6)

还有冲突

2021-04-06 09:37 UTC, fanhe-lg commented
tt

> > @RockLi 添加了idp api tags方便前端排序，解决了合并冲突[bff7a94](https://github.com/longguikeji/arkid/commit/bff7a94c6285eb0b0f20c835a2c1a83b37e586a6)
> 
> 还有冲突

又提交了commit

2021-04-06 11:36 UTC, RockLi approved these changes
LGTM

2021-04-06 11:36 UTC, RockLi commented on api/v1/serializers/external_idp.py
> +            external_idp.is_active = True
有get_or_create 可能是deleted的结果

2021-04-06 11:36 UTC, merged