Dockerfile
longguikeji/arkid pull request #264
Opened 2021-04-02 14:24 UTC by notevery

Dockerfile和jenkinsfile等文件，更新了pipfile，添加了dev依赖 pre-commit。

2021-04-02 14:58 UTC, RockLi commented on devops/jenkinsfile.dev
> +        // 在北京龙归科技有限公司这个钉钉群的机器人
应该是飞书群，同时该ID不应该出现在公开repo上

2021-04-02 14:59 UTC, RockLi commented on arkid/settings.py
> +if os.path.exists(os.path.join(BASE_DIR, 'settings_local.py')):
除了```settings_local.py```之外，还需要有```arkid.local.toml```文件

2021-04-02 15:00 UTC, RockLi commented
commit消息不符合规范

2021-04-02 15:00 UTC, RockLi commented on Dockerfile
> +WORKDIR /var/oneid
```oneid``` => ```arkid```

2021-04-02 15:01 UTC, RockLi requested changes
no more comments

2021-04-04 09:13 UTC, notevery commented on devops/jenkinsfile.dev
> +        // 在北京龙归科技有限公司这个钉钉群的机器人
添加了飞书的消息通知；
钉钉id是jenkins配置钉钉时随机生成的，不能直接调用钉钉。

2021-04-04 09:16 UTC, notevery commented on arkid/settings.py
> +if os.path.exists(os.path.join(BASE_DIR, 'settings_local.py')):
在arkid/settings.py 中已经有入口了，CONFIG_LOCAL_FILE = 'arkid.local.toml'。
在docker-compose和chart中添加了arkid.local.toml 文件：
https://github.com/longguikeji/arkid-charts/tree/v2-dev

2021-04-04 09:16 UTC, notevery commented on Dockerfile
> +WORKDIR /var/oneid
修改了workspace为 /var/arkid

2021-04-05 09:56 UTC, merged